lib/descriptor.js, test/test-descriptor.js
Hi,
The callback registered to listen to valueRead and valueWrite of descriptors are kept indefinitely which I believe is a typo. I've added tests and a fix. Please let me know if I'm missing something or if this behavior is intentional. Thanks.
And thanks for the brilliant module =)
=> fix firing callback more than once when read/writing descriptors

lib/linux/l2cap-ble.js
A pop() command was causing messages to be sent out of order. This needed to be a shift(), taking the first element of the array rather than the last.
=> Fixed out of order packets sent on Linux

lib/linux/hci-ble.js, lib/noble.js, src/l2cap-ble.c
After some promising tests I suddenly had some ugly Problems with SensorTag after a reboot. It just stopped working. `node test.js` resulted in a blinking cursor on the next line. 
A fresh checkout stopped with the new message about missing privilege.  
After setting the capabilities I got the blinking cursor again. Now I ran `DEBUG=* node test.js` with the following result: 
noble stateChange unsupported +0ms
That is strange. Before booting my BLE capable device was `hci1` and the default device was `hci0`. Now it is the other way round: default is `hci1` and `hci0` supports BLE. This was consistent across multiple boots. Probably something about Plug&Play. 
After using `NOBLE_HCI_DEVICE_ID=0  DEBUG=* node test.js` I got:
l2cap-ble BC:xx:xx:xx:xx:xx: line = connect Transport endpoint is …
=> Fix error handling and adapter binding

lib/mac/mavericks.js
periphal objects stored in `_peripherals` are no longer overwritten when repeated picked up while scanning
=> persistent peripherals between calls to .startScanning() on mavericks

lib/linux/hci-ble.js
If an advertising device changes its service UUIDs, the old and redundant ones remain cached - even if they are no longer being advertised. As far as I'm aware this isn't desired behaviour, but it was causing problems in a use case I was exploring. When the service data is cleaned up, the service UUIDs should be as well.  
In reality, only doing this every second event (as the implementation currently does), might not be wholly efficient as it could miss an instantaneous new service UUID - but will pick it up soon after anyway.
=> On Linux, refresh serviceUuids for incoming advertisement

README.md
Expands on description of `notify(true)` and `on('data')` to clarify the interaction
=> Clarifies notify misunderstanding in #208

lib/noble.js
Clearly not giving you trouble currently, but when I copied this code and ran it in react native it came up, so why not fix it.
=> fix this._discoveredPeripheralUUids = []; variable not initalized in constructor

lib/hci-socket/gap.js
It could happen (and it sometime does on my machine) that an the
_discoveries map does not contain the address when the type is 0x04
=> Fix a potential exception when accessing a non existent element

examples/peripheral-explorer.js
it was previously using localName to check.
=> fix serviceUuids var check in peripheral-explorer.js

README.md, lib/hci-socket/gap.js, lib/hci-socket/hci.js
This adds receiving HCI CMD packets and checking to see if they are scan enable commands. If they are, it checks to see if scan enable/disable and duplicate filtering settings are different then what the current script expects. If they are, a callback is issued so that the main script can take any necessary action.
Pull request for issue #300.
=> Check for changes to scanning

lib/hci-socket/gatt.js
Previously when looking for characteristics, all descriptors of the
related service were deleted. This caused a bug when messages on one of
the descriptors arrived before the descriptors were rediscovered. This
should fix it.
Please consider what consequences this change might have, as i don't have in-depth knowledge about noble, **and don't know if this might cause any new bugs**.
Fixed the following Bug for me:
`/root/node/node_modules/noble/lib/hci-socket/gatt.js:608`
`        this._descriptors[serviceUuid][characteristicUuid][descriptors[i].uuid] = descriptors[i];`
`                                                                                ^`
`TypeError: Cannot set property '2902' of undefined`
`    at null.<anonymous> (/root/node/node_modules/noble/lib/hci-socket/gatt.js:608:81)` …
=> Don't kill all descriptors when looking for new Characteristics

README.md, lib/noble.js, with-bindings.js
Some weeks ago I wrote basic Universal Windows Platform bindings for Noble. These bindings are available at https://github.com/hgwood/winble. They are still pretty raw.
While developing those bindings I found out there is no easy way to make Noble use bindings that it is not aware of. Basically you have to edit `noble.js`. I think it would be useful if Noble users (especially bindings developers) could optionally load any bindings they want and make Noble use them without editing its source.
This PR is an attempt to bring this feature to Noble without breaking the API. As of yet it is just a quick sketch of what I'm thinking of and I haven't tested it. Hopefully, from there, we can start a discussion.
=> Support for pluggable bindings

README.md, lib/hci-socket/gatt.js
See #377 
Patch 6701fc61c5c0f44b948d90f12013ea464baffc80 introduced default functionality in noble to send error responses for commands meant for peripheral roles. This is problematic for use with bleno, as all commands that bleno is meant to receive will send back REQ_NOT_SUPPORTED. 
The introduction of the NOBLE_MULTI_ROLE flag will prevent this functionality, as well as provide a flag for all future multi role patches to be placed under. 
Bryce
=> multi role - introduce NOBLE_MULTI_ROLE flag for ignoring peripheral role commands

lib/hci-socket/gatt.js
Working with some OS X based developers, we noticed the OS X backend automatically performs a "Write Long Characteristics Values" (spec section 4.9.4) operation if you write a characteristic value that's longer than the MTU.
Under the HCI backend on Linux, the characteristic value was truncated "on the wire" and an invalid Bluetooth PDU was sent.
This PR adds automatic "Write Long Characeristics" behaviour on Linux, to match the OS X behaviour (I believe this is spec compliant in both cases, section 4.9.4 doesn't put any restrictions on when it is to be used.)
Please let me know if I need to make stylistic/structure changes, I'm new to node.js.  Thanks for a very useful and powerful project!
=> Support "long writes" when using hci socket on Linux

lib/hci-socket/gap.js
As discussed, modified gap.js to extract the three types of solicitation service UUID fields.
=> Added extraction of the solicitation service UUID fields

README.md
Don't think it's supposed to flow onto the next row.
=> Fix platform table in README

lib/hci-socket/bindings.js, lib/hci-socket/hci.js, lib/hci-socket/signaling.js
Enabled for non-Linux or Linux user channel mode.
Fixes #468.
Can be tested via `npm install sandeepmistry/noble#l2cap-signaling`
=> [hci-socket] Add L2CAP signaling layer

lib/hci-socket/gap.js
Always set scan parameters before an active scanning.
Now scan parameters are only set when an hci device becomes ready : 
refer Hci.prototype.pollIsDevUp and this code that is called when device becomes up :
in hci.js l550 :
```
if (hciVer < 0x06) {
this.emit('stateChange', 'unsupported');
} else if (this._state !== 'poweredOn') {
this.setScanEnabled(false, true);
this.setScanParameters();
}
```
I would remove :
this.setScanEnabled(false, true);
this.setScanParameters();
and only set scan parameters when a scan is needed. 
But in code scan parameters response is used in device up processus, when it is received a :
this.emit('stateChange', 'poweredOn');
is sent.I would suggest emitting this event when all responses command sent in  pollIsDevUp have been received. But we can also sending …
=> Issue https://github.com/sandeepmistry/noble/issues/471

lib/hci-socket/gap.js, lib/hci-socket/hci.js
* Allows disable filtering of duplicates on NTC CHIP (filter at higher level)
* Support multiple reports per LE meta event advertising report
Fixes #469.
Can be tested via `npm install sandeepmistry/noble#ntc-chip-scan-workarounds`
=> [hci-socket] Workarounds for scanning with N.T.C. C.H.I.P

lib/hci-socket/bindings.js
if `init()` fails we don't want to try and clear up on exit because _usbDevice will be undefined.
=> Fix #502 - crash on exit if no BLE adaptor found on Windows

README.md
First entry is how to fix Error: Command disallowed with some BLE adapters when trying to connect.
=> Added 'Adapter specific known issues' section to the README. 

README.md, lib/resolve-bindings.js, package.json
Depends on sandeepmistry/node-bluetooth-hci-socket#48.
The discovery example works! (Tested on: FreeBSD/arm 11.0-STABLE + CSR8510 A10.)
=> Add FreeBSD support

lib/noble.js
According to README, when startScanning is passed a callback as a third argument, that callback is a usual Node-style "error first" callback.
But in fact, when scanning is started successfully, callback is called with `filterDuplicates` value as its first argument.
Here is an example situation where it causes problem:
```
// don't allow duplicates (as by default) but pass a callback
noble.startScanning([], false, function(error) {
if(error) {
console.log('Failed to start scanning:', error);
}
});
```
What happens when you run this code:
`Failed to start scanning: true`
This PR is intended to fix this.
=> Fix startScanning callback calling

lib/hci-socket/bindings.js
As helpful as it is to have the Status Mapper print out plain english error codes, It might also be nice to give users the HCI error code they're dealing with.  I found [this table](http://www.lisha.ufsc.br/teaching/shi/ine5346-2003-1/work/bluetooth/hci_commands.html) which seems to mirror what's returned in that status field - so in this PR, I convert `status` to a hex string and spit it out with the plaintext.
=> More descriptive error outputs

lib/noble.js
We merged the last change, but Im already seeing some oddness with folks who use the startscanning without waiting for (or even creating a listener on) statechange thus not having bindings init. Thinking about it more, someone might also be polling noble.state and would never init bindings either.
The only other public facing api is noble.stopScan but thats easier, if were not init, just dont call the bindings layer.
=> more work for lazy bindings

README.md, examples/peripheral-explorer.js, lib/mac/bindings.js, lib/mac/highsierra.js
The adafruit scanner seems to work on high sierra where LightBlue doesnt appear to be able to read characteristics.
You can play along at home if I missed your favorite xpcid.  I used [frida](https://www.frida.re/docs/installation/) instead of [swizzling](https://makezine.com/2014/01/03/reverse-engineering-the-estimote/), because I couldnt get swizzling to work. I think maybe the CBXpcConnection are now private and maybe they used to be public? but I had never done it before so it could be my failure.
For frida
```
$ frida-trace -m "-[CBXpcConnection sendMsg:args:]:"  -m "-[CBXpcConnection _handleMsg:]" *Adafruit*
Instrumenting functions...                                              
-[CBXpcConnection sendMsg:args:]: Loaded handler at …
```
=> High Sierra support

lib/hci-socket/gatt.js, lib/mac/highsierra.js, lib/mac/mavericks.js, lib/mac/yosemite.js
... when calling discoverCharacteristics multiple times in a program.
Without this fix, we get crashes when unsubscribing, and never receive 'data' events on previously subscribed characteristics if calling discoverCharacteristics multiple times with different uuid lists.
This PR includes comments/feedback from #730
=> Don't forget previously discovered characteristics

lib/noble.js
By setting the initialized flag to true before calling init.
Fixes #765.
=> Fix multiple init of bindings
